export enum ServiceErrorCode {
    // Booking Service
    RESIDENT_NOT_FOUND = 'RESIDENT_NOT_FOUND',
    BOOKING_BLOCKED = 'BOOKING_BLOCKED',
    BLOCK_UNAVAILABLE = 'BLOCK_UNAVAILABLE',
    DOUBLE_BOOKING_DETECTED = 'DOUBLE_BOOKING_DETECTED',
    PAST_TIME = 'PAST_TIME',
    BUILDING_MISMATCH = 'BUILDING_MISMATCH',
    BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',
    UNAUTHORIZED_CANCELLATION = 'UNAUTHORIZED_CANCELLATION',
    CANNOT_CANCEL_COMPLETED_BOOKING = 'CANNOT_CANCEL_COMPLETED_BOOKING',
}
